### ISSUE TITLE
DefaultResponseExceptionMapper seems wrong

### ISSUE THREAD

**Issue by Ladicek** [heiko-braun/mp-rest-client-impl#1]
I'm quickly going through the code and found a suspicious line here: https://github.com/heiko-braun/mp-rest-client-impl/blob/master/impl/src/main/java/org/wildfly/swarm/microprofile/restclient/DefaultResponseExceptionMapper.java#L22 `status>400` definitely looks strange, and the MP spec https://github.com/eclipse/microprofile-rest-client/blob/master/spec/src/main/asciidoc/providers.asciidoc confirms that it should be `>= 400`.

**Comment by heiko-braun** [comment]
good catch @Ladicek. it's always worth awaiting your review.
